name: Update Team Members


# Run this action at 11:00 (3 am Pacific) on the first Thursday of the month.
# on:
#   schedule:
#     - cron:  '0 11 * * 4 [ $(date +\%d) -le 7 ] && command'
on: [push] ' [ $(date +\%d) -le 7 ] && command '


jobs:
  # This workflow contains a single job called "trim_contirbutors"
  trim_contributors:
    runs-on: ubuntu-latest

    # if: github.repository == 'hackforla/website'
    if: github.repository == 'alexeysergeev-cm/website'

    steps:
    # checkout repo
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # install dependencies to run js file
    - name: GitHub Action for install npm dependencies
      uses: bahmutov/npm-install@v1
      with:
        working-directory: ./github-actions/github-data

    # run js file
    - name: Trim Members
      env:
        token: ${{ secrets.PAT }}
      run: node github-actions/github-data/contributors-data.js
