# This workflow is triggered every day at 2 am Pacific (10 am UTC)

name: Update Contributors 

on:
  schedule:
    # - cron: '0 10 * * *'
    - cron: '*/1 * * * *'


jobs:
  # This workflow contains a single job called "trim_contirbutors"
  trim_contributors:
    runs-on: ubuntu-latest
    if: github.repository == 'alexeysergeev-cm/website'


    steps:
    # Runs a single command using the runners shell      
    # - name: Checkout repository
    #   uses: actions/checkout@v2
    #   with:
    #     token: ${{ secrets.TEST_TOKEN }}

    # - name: Checkout repository
    #   uses: actions/checkout@v2
    #   with:
    #     token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}

    - name: Work with contributors-data
      env:
        token: ${{ secrets.TEST_TOKEN }}
      # run: node github-actions/github-data/contributors-data.js
      runs:
        using: 'node12'
        main: 'github-actions/github-data/contributors-data.js'