name: Update Team Members


# Run this action at 11:00 (3 am Pacific) on day-of-month 1 and 15.
# on:
#   schedule:
#     - cron:  '0 11 1,15 * *'
on: [push]

jobs:
  # This workflow contains a single job called "trim_contirbutors"
  trim_contributors:
    runs-on: ubuntu-latest

    if: github.repository == 'hackforla/website'
    if: github.repository == 'alexeysergeev-cm/website'

    steps:
    # checkout repo
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # install dependencies to run js file
    - name: GitHub Action for install npm dependencies
      uses: bahmutov/npm-install@v1
      with:
        working-directory: ./github-actions/github-data

    # run js file
    - name: Trim Members
      env:
        token: ${{ secrets.PAT }}
      run: node github-actions/github-data/contributors-data.js


    # do I need auto commit here with help of the BOT? 

    # - name: Auto Commit
    #   uses: stefanzweifel/git-auto-commit-action@v3.0.0
    #   with:
    #     # Optional glob pattern of files which should be added to the commit
    #     file_pattern: _data/external/github-data.json

    #     commit_message: Update contributor and language data

    #     # Commit author settings
    #     commit_author: GitHub Actions Bot <hackforla-bot@hackforla.org>