# This workflow is triggered every day at 2 am Pacific (10 am UTC)

name: Update Contributors 

on:
  schedule:
    # - cron: '0 10 * * *'
    - cron: '*/1 * * * *'


jobs:
  # This workflow contains a single job called "trim"
  trim:
    runs-on: ubuntu-latest

    if: github.repository == 'alexeysergeev-cm/website'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell      
    # - name: Checkout repository
    #   uses: actions/checkout@v2
    #   with:
    #     token: ${{ secrets.TEST_TOKEN }}

    # - name: Checkout repository
    #   uses: actions/checkout@v2
    #   with:
    #     token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}

    - name: Work with contributors-data
      env:
        token: ${{ secrets.TEST_TOKEN }}
      run: node github-actions/github-data/contributors-data.js