name: Update Team Members


# Run this action at 11:00 (3 am Pacific) on the first Thursday of the month.
# on:
#   schedule:
#     - cron:  0 11 * * 4 
on: push


jobs:
  # This workflow contains a single job called "trim_contirbutors"
  trim_contributors:
    runs-on: ubuntu-latest

    # if: github.repository == 'hackforla/website'
    if: github.repository == 'alexeysergeev-cm/website'

    steps:
    # get day number of the month
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +\%d)"

    # checkout repo
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    # setup node and install dependencies to run js file
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install
      working-directory: ./github-actions/github-data

    # run js file if it is the first Thursday of the month
    - name: Trim Members
      env:
        # token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
        token: ${{ secrets.PAT }}
      if: ${{ steps.date.outputs.date <= 7 }}
      run: node github-actions/github-data/contributors-data.js
